[package]
name = "hyper-openssl"
version = "0.4.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]
description = "Hyper SSL support via OpenSSL"
license = "MIT/Apache-2.0"
repository = "https://github.com/sfackler/hyper-openssl"
readme = "README.md"

[dependencies]
antidote = "1.0.0"
hyper = { version = "0.11.0", default-features = false }
openssl = "0.10"
tokio-core = "0.1.8"
tokio-io = "0.1.2"
tokio-openssl = "0.2"
tokio-service = "0.1.0"
futures = "0.1.14"
