[package]
name = "hyper-openssl"
version = "0.7.1"
authors = ["Steven Fackler <sfackler@gmail.com>"]
edition = "2018"
description = "Hyper TLS support via OpenSSL"
license = "MIT/Apache-2.0"
repository = "https://github.com/sfackler/hyper-openssl"
readme = "README.md"
exclude = ["test/*"]

[features]
default = ["runtime"]

runtime = ["hyper/runtime"]

[dependencies]
antidote = "1.0.0"
bytes = "0.4"
hyper = { git = "https://github.com/hyperium/hyper", default-features = false }
lazy_static = "1.0"
linked_hash_set = "0.1"
openssl = "0.10.19"
openssl-sys = "0.9.26"
tokio = { git = "https://github.com/tokio-rs/tokio" }
tokio-openssl = { git = "https://github.com/sfackler/tokio-openssl", branch = "tokio-02" }

[dev-dependencies]
futures-preview = "0.3.0-alpha.17"
hyper = { git = "https://github.com/hyperium/hyper" }
