[package]
name = "hyper-openssl"
version = "0.8.1"
authors = ["Steven Fackler <sfackler@gmail.com>"]
edition = "2018"
description = "Hyper TLS support via OpenSSL"
license = "MIT/Apache-2.0"
repository = "https://github.com/sfackler/hyper-openssl"
readme = "README.md"
exclude = ["test/*"]

[features]
# FIXME should not be turning on http1 by default: https://github.com/hyperium/hyper/issues/2376
default = ["hyper/http1", "tcp"]

tcp = ["hyper/tcp"]

[dependencies]
http = "0.2"
hyper = { version = "0.14", default-features = false, features = ["client"] }
linked_hash_set = "0.1"
once_cell = "1.0"
openssl = "0.10.32"
openssl-sys = "0.9.26"
parking_lot = "0.11"
tokio = "1.0"
tokio-openssl = "0.6"
tower-layer = "0.3"

[dev-dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
