[package]
name = "hyper-openssl"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]
description = "Hyper SSL support via modern versions of openssl"
license = "MIT/Apache-2.0"
repository = "https://github.com/sfackler/rust-hyper-openssl"
documentation = "https://docs.rs/hyper-openssl/0.1.0/hyper_openssl"
readme = "README.md"

[dependencies]
antidote = "1.0"
hyper = { version = "0.9", default_features = false }
openssl = "0.9.2"
